name: nicochess
description: Basic chess engine for board validation and move generation.
homepage: https://github.com/alexrintt/nicochess
repository: https://github.com/alexrintt/nicochess
issue_tracker: https://github.com/alexrintt/nicochess/issues
documentation: https://pub.dev/packages/nicochess
version: 0.1.0
funding:
 - https://github.com/sponsors/alexrintt

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  fast_immutable_collections: ^9.0.0
  meta: ^1.8.0

dev_dependencies:
  lint: ^2.0.1
  test: ^1.22.1
